name: Build
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v2
              with:
                  node-version: "12.x"
            - name: Install and Build 🔧
              run: | # Install npm packages and build the Storybook files
                  yarn install
                  yarn build
                  yarn build-storybook --quiet
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.6.2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: public # The folder that the build-storybook script generates files.
                  CLEAN: true # Automatically remove deleted files from the deploy branch
